### ISSUE TITLE
Modules and options install scripts using wrong comparison operator

### ISSUE THREAD

**Issue by taliesins** [Nevuly/WSL2-Linux-Kernel-Rolling-LTS#1]
I was unable to run the modules and options install in WSL Ubuntu 22.04. I think the problem is that `-eq` is being used instead of `==`. `-eq` is for comparing numbers

https://stackoverflow.com/questions/20449543/shell-equality-operators-eq

This is what I did to fix the install scripts:

https://gist.githubusercontent.com/Nevuly/cf1d17db72cdfde6ed149461eef0215c/raw/8d16f84a8b3a7b815dd13c0af8768cd6ef31712c/modules-install.sh
```
sed -i 's/-eq /== /' ./modules-install.sh
```
https://gist.githubusercontent.com/Nevuly/b203682442ba2c6cf4cad3b35afb6f4b/raw/6a04daf739a983f1a41099effbeb398f04a63145/optionals-install.sh

```
sed -i 's/-eq /== /' ./optionals-install.sh
```

**Comment by Nevuly** [comment]
@taliesins 

I'll update install scripts to change about that.

Thanks for your report!

**Comment by Nevuly** [comment]
Applied in this commits

Stable: https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/commit/c2ee3f28df869f3a9c21335866cd3a9122932ccf
LTS: https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling-LTS/commit/81224972db579327c6d18ffee1ea5ab98b1b95f9
